#!/bin/bash

#functions dbms
readonly DBS="databases";

function createDB {
    read -p "Enter Database Name : " dbName;
	if [[ ! -d $DBS/$dbName ]];
	then 
           mkdir $DBS/$dbName;
		if [[ $? == 0 ]]; 
		then
		  echo $dbName" Database Created Successfully" ;
		else	
		 echo "Error Done While Creating the Database" ;
		fi
	else	
	  echo "This Database is Exists";
	fi

}
function dropDB {
  read -p "Enter Database Name : " dbName;
   rm -r $DBS/$dbName 
	  if [[ $? == 0 ]];
	  then
	    echo "Database Dropped Successfully"
	  else
	    echo "Database Not found"
	  fi
	 
}
function displayTable {
    read -p "Enter Database Name : " dbName;
    read -p "Enter Table Name : " tableName;
	if [[ -f $DBS/$dbName/$tableName ]];
	then 
           cd $DBS/$dbName
	   cat $tableName
	else
           echo "Table Not found";
	fi
}
#Under development (datatypes)
function sortTable {
    read -p "Enter Database Name : " dbName;
    read -p "Enter Table Name : " tableName;
    
	if [[ -f $DBS/$dbName/$tableName ]];
	then 
	 read -p "Enter Field Name that You Want Sort By It " Field
	 read -p "Enter ASC For Ascend​ing , DESC For Descending " choice
	   if [[ $Field == String ]]
	   then
		  case $choice in
			ASC)
			  sort $tableName;;
			DESC) 
		          sort -r $tableName;;
			*) echo "error"
		  esac
	   else
                  case $choice in
			ASC)
			  sort -n $tableName;;
			DESC) 
		          sort -nr $tableName;;
			*) echo "error"
		  esac
           fi 
	else
           echo "Table Not found";
	fi
}



#function show menu
show_menus() {
	
	echo "~~~~~~~~~~~~~~~~~~~~~"	
	echo " D B M S- M E N U"
	echo "~~~~~~~~~~~~~~~~~~~~~"
        echo "1. Create Database"
	echo "2. List Datebases"
	echo "3. Drop Datebase"
	echo "4. Create Table"
	echo "5. Alter Table"
	echo "6. Add Record"
	echo "7. Edit Records"
	echo "8. Delete Records"
	echo "9. Select Records" 
        echo "10. Display Table"
	echo "11. Sort Table"
	echo "12. Drop Table" 
	echo "13. Exit"
}

#function read
read_options(){
	local choice
	read -p "Enter choice [ 1 - 13 ] " choice
	case $choice in
		1)createDB;;
		2)ls $DBS;;
		3)dropDB;;
		4) ;;
		5) ;;
		6) ;;
                7) ;;
		8) ;;
		9) ;;
		10)displayTable;;
		11)sortTable;;
		12);;
		13) exit 0;;
		*) echo "error"
	esac
}

while true
do
 
	show_menus
	read_options
done

